# Generated by Django 3.2.5 on 2022-01-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220116_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_createted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default=727439),
        ),
    ]
